addons:
  apt:
    packages:
    - curl
    - xvfb

script:
- npm install
- npm build
- nohup Xvfb :66 -ac &
- export DISPLAY=:66
- npm test

notifications:
  slack: gdsa2015:kNg7P3o0KbDnPEJL1Q5tnd6b
